### ISSUE TITLE
Enhance background color picker

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-tile-editor#1]
Currently the background color picker is just a few ugly buttons

We could replace it with a dropdown that has:
- a pallete of few nice colors
- a text input for manual entrance of a color in `#ffffff` format
- a `<input type="color">` that opens the system color picker (demo http://jsfiddle.net/warpech/xuhZv/27/)

**Comment by warpech** [comment]
Did you push the changes? I can't find it

**Comment by ghost** [comment]
@warpech I did not push anychanges... i may accidently closed this issue by misstake, not really sure how that happend.
