### ISSUE TITLE
Consider using linqjs

### ISSUE THREAD

**Issue by miyconst** [Juicy/juicy-tile-editor#100]
@tomalec, @warpech, working on the `juicy-tile-simple-editor` I would like to use [linqjs](https://github.com/miyconst/linqjs).

What do you think? Is it a good idea? @tomalec's main concern was that the library modifies `Array.prototype`. 

I can replace it with a `linq` function:
#### The array

``` js
var items = [{ name: "item 0", value: 0 }, { name: "item 1", value: 1 }, { name: "item 2", value: 2 }, { name: "item 3", value: 3 }];
```
#### With `Array.prototype`

``` js
var filtered = items.where("x => x.value > 1");
```
#### Without `Array.prototype`

``` js
var filtered = lq(items).where("x => x.value > 1").get();
```

---

I really miss `orderBy`, `where`, `first`, and `group` functions.

**Comment by warpech** [comment]
This can be achieved with zero dependencies 

``` js
items.filter(function(x) { return (x.value > 1) });
```

If it helps you with prototyping then temporarily use linqjs, but for final version I prefer to stick with plain JS for two reasons:
1. I am unfamiliar with Linq, which is not native concept in JS world. It feels is a bit like [php.js](http://phpjs.org/), which is every PHP developers' favourite JS library before they forget about PHP.
   - functionalities asked by you (filter, orderBy, first, groupBy) are available in widely known [lodash](https://lodash.com/docs) (it also has method chaining), but I would also like to avoid using that 
2. Performance reasons

Your code in linqjs is very smart, but brings in performance penalties. Compiling a function from a string is no different from an `eval`. From what I know, the mere presence of `eval` disqualifies the function (and affected calls) from JIT optimization.

In my Firefox, linqjs is 600 times slower than `Function.prototype.filter`: http://jsperf.com/filter-vs-function-constructor

**Comment by miyconst** [comment]
@warpech thank you for the input.

All the methods I mentioned above also support pure js functions, you don't necessary need to write linq strings. I like this notation because it is short and elegant, and in [fact](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Arrow_functions) is a part of the new js standard.

``` js
var filteredAndSorted = items.where("x=>x.value > 1").orderBy("x=>x.name");
```

Is just a shortcut for:

``` js
var filteredAndSorted = items
    .where(function (item, index) { 
        return item.value > 1; 
    })
    .orderBy(function (item, index) { 
        return item.name; 
    });
```

But I stick with pure js, as you don't like it and @tomalec also does not seem to be happy with it.

Closing the issue.

**Comment by tomalec** [comment]
Once Safari nad IE will get into pace, you can use native arrow functions instead of stringified ones.
http://caniuse.com/#search=arrow%20functions

But, for the same reasons I'd like to avoid ES6, transpilers, & co. not to end up with Aurelia-like process

**Comment by miyconst** [comment]
Yeah, I just linked the arrow functions in my previous comment.

> ... and in [fact](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Arrow_functions) is a part of the new js standard
