### ISSUE TITLE
Integrate juicy-tile-grid@1.3.0

### ISSUE THREAD

**Issue by tomalec** [Juicy/juicy-tile-editor#101]
Thanks, to https://github.com/Juicy/juicy-tile-grid/releases/tag/1.3.0
some code for setup manipulation could (and needs) be cleaned up.
We no longer need to bother that much about refreshing `juicy-tile-*` after changing/resetting `.setup`.

compatibility notes are at https://github.com/Juicy/juicy-tile-list/issues/45#issuecomment-172663084

@miyconst, Could you take it?

**Comment by miyconst** [comment]
Taking this on me.

**Comment by miyconst** [comment]
@tomalec `juicy-tile-editor` does not use those features. It only sends `true` to `list.refresh` method when needed, and this has not been changed.

On other hand `juicy-tiles-setup-sync` did call `list.setupChanged` explicitly. It is fixed now.
