### ISSUE TITLE
Refresh tree items order when moving tiles up and down

### ISSUE THREAD

**Issue by miyconst** [Juicy/juicy-tile-editor#104]
When moving tiles up and down the side tree items should also be sorted.

**Comment by tomalec** [comment]
are you aware that priority does not necessarily match x,y visual order due to bin-packing?

**Comment by miyconst** [comment]
Yes, I am aware. Most of the times it is same order, and even if some times have different order it is still better to show wrong a couple of tiles, than entire tree.

**Comment by tomalec** [comment]
Cool, I would not say 

> wrong a couple of tiles
> but rather that we **list** items in a tree precisely according to the priority, and we **pack** items into a space also according to the priority.

An this would be nice way to finally show this real priority to the user.

**Comment by miyconst** [comment]
Yeah, this is what I already did. Not yet pushed though.
