### ISSUE TITLE
Provide design for advanced and weird modes

### ISSUE THREAD

**Issue by miyconst** [Juicy/juicy-tile-editor#105]
We should decide which controls of current editor goes to "advanced" and "weird" section.

cc @warpech, @tomalec, @Starcounter-Jack

**Comment by warpech** [comment]
Me and @miyconst made some design on paper.

Additional comments:
- "Reset" should have only one action (explained on picture)
- "Tight" group should be renamed to "Own scope" and be ON by default
- "Oversize" input should be moved to "Fill"

![artboard 1](https://cloud.githubusercontent.com/assets/566463/12449456/ac3feadc-bf7d-11e5-84fa-a8bbbe3b3901.png)

**Comment by tomalec** [comment]
LGTM

**Comment by miyconst** [comment]
The design is implemented in simple way. The UI has its own issue: https://github.com/Juicy/juicy-tile-editor/issues/98, closing this one.
