### ISSUE TITLE
Do not translate 1/12 to 8.33%

### ISSUE THREAD

**Issue by tomalec** [Juicy/juicy-tile-editor#109]
As then In layout with 
`4/12 + 4/12 + 4/12` - which is supposed to produce 3 equal columns that occupy entire space - produce 4 columns. 
The last one may get stretched (in upper boundary of element query), to few pixels, and considering gutters, we may loose proportions between tiles.

We can fix that either by using float with better precision, or by expressions that we planned to implement.

**Comment by miyconst** [comment]
What precision would be enough to avoid this issue? I can easily change the value to whatever is required.

**Comment by tomalec** [comment]
I think JS default precision of `1/12` is enough.
