### ISSUE TITLE
Simplify dimensions controls

### ISSUE THREAD

**Issue by tomalec** [Juicy/juicy-tile-editor#116]
As agreed on today's (2016-02-04) meeting with @Starcounter-Jack, @warpech, @miyconst and me, we would like to simplyfy dimension controls, and reduce the fixed/flexible/%/px/Number confusion.

End results looks in in here:
![20160204_163039](https://cloud.githubusercontent.com/assets/17435/12829622/6e209cdc-cb8b-11e5-86ff-a98a771c4a62.jpg)

The width control(set) will contain:
- input field for numeric value,
- `px/%` toggle, where `px` means the size given by number will be fixed regardless of content or container changes, `%` means the size is flexible, related to container size, it will also take gutter into account,
- calculator icon, that will give you expressions editor, so you could get the results of current "fixed %", and "flexible number", and many more, by expressions like: `100 * ($parent - 123px) / parent`, right now users would need to use manual calculator,

height control will additionally, get 
- "grows with content" - which will change the label from "width" to "min-width", and set `heightDynamic: true`. This time we will limit this to really "grow only", so `heightDynamic` set row to be have `min-height: NNNpx`, and to grow with content. We do so as we need some value for bin-packing, but we removed pre-calculate phase, and we didn't implement editor's precalculation.
  If somebody would like to achive re-sizing from 0, he/she could set height to `1px` or even `0.0000001px` so it will be rounded by browser to `0px`, but the bin-packing will get something `>0`

We could support "grows with content" for width in grid layout, but the behavior with `<table>` fallback is so ugly, that's better to hide it.

**Comment by miyconst** [comment]
@tomalec you are a workaholic, just back from lunch and creating issues :).

**Comment by warpech** [comment]
Calculator Phase 1:
calculator icon acts as previous "calculate" button

Calculator Phase 2:
calculator icon opens a dropdown with:
- textarea, where you can write a math expression with `parent` and `content` helper variables
- button that executes the expression and puts the result as width (height) value
- additionally buttons with sample expressions

**Comment by miyconst** [comment]
https://github.com/Juicy/juicy-tile-editor/commit/8808762331bc0fe86b1f2fa36006dfee718291bf

**Comment by miyconst** [comment]
Done.

The new look:

![image](https://cloud.githubusercontent.com/assets/6435556/13048473/563ae420-d3e6-11e5-8b76-0dd57fc46d2b.png)

Closing this issue to avoid repolepsy. The _Calculator Phase 2_ is moved to another issue: https://github.com/Juicy/juicy-tile-editor/issues/125.
