### ISSUE TITLE
Fix priority issue for empty groups

### ISSUE THREAD

**Issue by miyconst** [Juicy/juicy-tile-editor#118]
When a new group created its priority is equal to the selected tile or 1, which makes the tiles with same priority not movable up/down.

**Comment by tomalec** [comment]
I think as you use `createNewContainer` (https://github.com/Juicy/juicy-tile-list#methods) when creating _rectangle_, you need to specify the priority, and do not just copy its container/selected tile, but for example if you mean adding new group before selected element, you can add `Number.EPSILON` or, if you would like to add it after subtract `EPSILON`

**Comment by tomalec** [comment]
What's more it may happen in many other ways, that priority is `1` (or `0`) for two different elements (for example, when two apps' setups will be merged) and the only solution I see is to select one of them in the editor and click down (up) button.

**Comment by miyconst** [comment]
I don't understand how merged setup differ from single app setup in terms of layout editor. For editor it is still one partial. And the automatic priority will be set correctly.

The issue with new groups is fixed now.

**Comment by tomalec** [comment]
It is, that's why editor will produce values correctly. The problem is with values delivered.

Consider setup for app A:

```
a1.priority = 0.5
a2.priority = 0.3
```

and layout for app B:

```
b1.priority = 0.9
b2.priority = 0.6
b3.priority = 0.3
```

If those two get's merged we will end up with two tiles a2 and b3 with same priority.

**Comment by miyconst** [comment]
Potentially yes, but I still don't think how that could be possible.

We have a partial, which is loaded with 

``` html
<starcounter-include partial="{{model.Product}}">
```

The partial has name, for example `/Products/ProductPage.html`.

In the database we save setup for the partial, which is 

``` js
{ key: "/Products/ProductPage.html", value: { items: [a1, b1] } }`
```

Now we start Images application, which adds some HTML to the partial. We will see some more non-styled tiles on the screen, but saved setup for the partial won't change. And we also not able to mix tiles between partials.

That is why I don't see how we could keep two setup values for same partial for different apps.

**Comment by tomalec** [comment]
1. We planned long time agou to be able to add sophisticatedfeature to editor, to save layout per:
   - just partial
   - partial according to set of apps running
   - ...
   
   Then we will build suggested ones based on existing matrix etc.
2. Soon (hopefully this week), we will be able to provide suggested layouts based on hints given by developers. So, app devs will pride such layouts.
3. Even now it should be possible:
   -  We have stored `{ key: "/Products/ProductPage.html", value: { items: [a1, a2, b1, b2, b3] }`}`
   - start the editor with only app A running,
   - change the priorities to `a1.priority=0.5; a2.priority = 0.3;`
   - close app A, start the editor with only app B running,
   - change the priorities to `b1.priority=0.9; b2.priority = 0.6; b3.priority = 0.3;`
   - start app A

**Comment by miyconst** [comment]
> 1, 2

Out of the scope of this issue.

> 1. Even now it should be possible:

Even though the app A is not running, the saved tiles will still be in the setup. Am I wrong?

**Comment by tomalec** [comment]
Why 2. is out of scope of this issue?

**Comment by miyconst** [comment]
This issue covers priority issues which are caused by `juicy-tile-editor` itself, by creating groups with same priority.

About the developer hints, I don't recall we had something for priority. The DOM elements order is the suggested priority by the developer.

**Comment by tomalec** [comment]
I think technically dev hints may contain any property used by `juicy-tile-*`, and even order in DOM translated to priority may cause us same problems

**Comment by miyconst** [comment]
Yes, technically there is a chance to end up with such setup. I think it should be resolved on `juicy-tile-list` level, not by the editor. If you think it's right time to address this issue, then create a task in the appropriate repository please.
