### ISSUE TITLE
Lose groups in juicy-tile-table

### ISSUE THREAD

**Issue by miyconst** [Juicy/juicy-tile-editor#134]
Right now editor does not support lose groups in `juicy-tile-table`. Original issue: https://github.com/StarcounterPrefabs/Launcher/issues/204.

@tomalec is it possible to add specific class to each `<tr>` which belongs to a group?

For example:
- **group_1** items [`0`, `1`]
- **group_0** items [`group_1`, `2`, `3`]

``` html
<tr class="juicy-tile-group-group_0 juicy-tile-group-group_1">
    <td class="juicy-tile-0"></td>
    <td class="juicy-tile-1"></td>
</tr>
<tr class="juicy-tile-group-group_0">
    <td class="juicy-tile-2"></td>
    <td class="juicy-tile-3"></td>
</tr>
```

Am I right that a `<tr>` is not split-able between groups? Means a `<td>` of a `<tr>` belongs to group `A` and another `<td>` of the same `<tr>` belongs to group `B`?

**Comment by tomalec** [comment]
Well, personally, I do not think we need to push editor problems into `juicy-tile-*` especially that we would like `juicy-tile-*` to work extremely fast, and we do not mind if `-editor` loads a little bit longer.

Can you just use `.allItems` property to get the rectangle for loose group, then (create an absolute positioned element to) highlight it, and pick all its `.items` to attach mouse over listeners?

> Am I right that a `<tr>` is not split-able between groups? Means a `<td>` of a `<tr>` belongs to group A and another `<td>` of the same `<tr>` belongs to group B?

You are right.

**Comment by miyconst** [comment]
> Can you just use .allItems property to get the rectangle for loose group, then (create an absolute positioned element to) highlight it, and pick all its .items to attach mouse over listeners?

Yes, I can, just thought of some simplification, didn't think of the performance :(.

**Comment by miyconst** [comment]
I have discovered that tiles may drop into gutter of a lose group. That is why I decided to highlight only tiles inside the lose group, not the entire rectangle.

Looks like this:

![image](https://cloud.githubusercontent.com/assets/6435556/13469220/ae8edb78-e0a6-11e5-97ed-6294ebc7b8b9.png)

**Comment by tomalec** [comment]
Could you post the json to reproduce tiles falling into gutter?

**Comment by miyconst** [comment]
Just scope in the Suppliers group and change gutter to something more than 11.

``` json
{"gutter":10,"width":1200,"direction":"horizontal","items":[{"width":"100%","widthFlexible":true,"id":"group_1","hidden":false,"heightDynamic":true,"height":1,"tightGroup":false,"priority":1,"gutter":0,"direction":"horizontal","items":[{"width":"225","widthFlexible":false,"id":0,"hidden":false,"heightDynamic":true,"height":1,"priority":0.9},{"width":"225","widthFlexible":true,"id":1,"hidden":false,"heightDynamic":true,"height":1,"priority":0.81},{"width":"100%","widthFlexible":true,"id":12,"hidden":false,"heightDynamic":true,"height":1,"priority":0.8}]},{"width":"100%","widthFlexible":true,"id":2,"hidden":false,"heightDynamic":true,"height":1,"priority":0.7},{"width":"100%","widthFlexible":true,"id":3,"hidden":false,"heightDynamic":true,"height":1,"priority":0.6},{"width":"100%","widthFlexible":true,"id":4,"hidden":false,"heightDynamic":true,"height":1,"priority":0.5},{"width":"100%","widthFlexible":true,"id":"group_2","hidden":false,"heightDynamic":true,"height":1,"tightGroup":false,"priority":0.41,"gutter":15,"direction":"horizontal","items":[{"width":"100%","widthFlexible":true,"id":5,"hidden":false,"heightDynamic":true,"height":1,"priority":0.4},{"width":"100%","widthFlexible":true,"id":6,"hidden":false,"heightDynamic":true,"height":1,"priority":0.31}]},{"width":"100%","widthFlexible":true,"id":7,"hidden":false,"heightDynamic":true,"height":1,"priority":0.3},{"width":"100%","widthFlexible":true,"id":8,"hidden":false,"heightDynamic":true,"height":1,"priority":0.2},{"width":"100%","widthFlexible":true,"id":"group_3","hidden":false,"heightDynamic":true,"height":1,"tightGroup":true,"priority":0.1,"gutter":0,"direction":"horizontal","items":[{"width":"100%","widthFlexible":true,"id":9,"hidden":false,"heightDynamic":true,"height":1,"priority":0.09},{"width":"100%","widthFlexible":true,"id":10,"hidden":false,"heightDynamic":true,"height":1,"priority":0.08}]},{"width":"100%","widthFlexible":true,"id":11,"hidden":false,"heightDynamic":true,"height":1,"priority":0.07}],"id":"root","precalculateHeight":true,"background":null}
```
