### ISSUE TITLE
Add code comments for simple editor

### ISSUE THREAD

**Issue by tomalec** [Juicy/juicy-tile-editor#140]
@miyconst Could you add some code comments? 

It's quite hard for me to dive into the code and add some features for the editor as for example [/src/juicy-tile-simple-editor.js](https://github.com/Juicy/juicy-tile-editor/blob/gh-pages/src/juicy-tile-simple-editor.js) has only 1664 lines of code, ~158 functions, but only  6 short comments

**Comment by miyconst** [comment]
Sure, assigning this one on me.

**Comment by miyconst** [comment]
@tomalec I have added description to every method in the file. Hope this helps. Take a look please.

**Comment by tomalec** [comment]
Why you have used XML instead of regular jsdoc format? In my opinion it's more widely used across JS project, easier to write and read by human, handled nicely by any editor I have used, works nice with JS tools to generate documentation out of it and we used it in all other elements.

Plus it requires **less _ code** ;)

**Comment by miyconst** [comment]
Probably because of my Microsoft Stack background. Got used to such comments too much :). I will change it to jsdoc format, as it seems be more reasonable.

**Comment by miyconst** [comment]
I converted the comments to `jsdoc` format with this tool http://patik.github.io/xmltojsdoc/.

**Comment by miyconst** [comment]
@tomalec, can you close this issue if you are satisfied with the comments?

**Comment by tomalec** [comment]
Could you also describe properties, as I'm still not sure for example what `selectedScope` should reflect?

**Comment by miyconst** [comment]
Done.

**Comment by tomalec** [comment]
Thanks that helped a lot :)
