### ISSUE TITLE
After editor is closed, juicy-tile-* is unusable, highlight still works

### ISSUE THREAD

**Issue by tomalec** [Juicy/juicy-tile-editor#142]
1. Go to http://juicy.github.io/juicy-tile-editor/examples/juicy-tile-table/simple.html
2. Close the editor using `(-)` icon
3. Click on anything inside `juicy-tile-table`

![juicy-tile-simple-editor _ - http___127 0 0 1_predefined_layouts_juicy-til](https://cloud.githubusercontent.com/assets/17435/13916286/fb0d1156-ef59-11e5-92bd-fb518ad19b1f.png)

**Comment by miyconst** [comment]
@tomalec provide some more details please. I can't reproduce the issue. If it's still the same for you, then I will have to look at your pc.

**Comment by tomalec** [comment]
Seems it was fixed in meantime
