### ISSUE TITLE
Prototype properties are shared among instances

### ISSUE THREAD

**Issue by tomalec** [Juicy/juicy-tile-editor#143]
Object-like properties defined in https://github.com/Juicy/juicy-tile-editor/blob/gh-pages/src/juicy-tile-simple-editor.js#L434 are shared among all instances what may lead to really weird behavior if on of many(two) instances will change default value (then the values will be changed for all other instances)

I think we should create new instances for those object once element is created.

@miyconst could you take a look at it?

**Comment by miyconst** [comment]
@tomalec are you talking about the `notAvailable` variable?

**Comment by tomalec** [comment]
I'm talking about:
- mediaScreenRanges
- widthRanges
- listSelectors
- selectedScopeItems
- breadcrumb

**Comment by tomalec** [comment]
All we need to do is something like https://github.com/Juicy/juicy-tile-editor/blob/RebelsLounge/issues/14-predefined_forms/src/juicy-tile-simple-editor.js#L477

```
value: function(){return {};}
```

I see no reason why we shouldn't allow multiple instances per page.

Then, if I add editor for my own stuff in my shadow dom - for example to select `tomalec-tile-3d-cube` instead - it doesn't mean that Launcher's `juicy-tie-editor` should stop selecting `juicy-tile-lists`

**Comment by miyconst** [comment]
Done. I wrapped all array properties into a function.

**Comment by tomalec** [comment]
Do you think 

``` js
getArrayPropertyValue([])  
```

plus function definition is easier to understand and write than

``` js
function(){return []}
```

or even, once we will get ES6

``` js
() => []
```

, or do we need those default values somewhere else?

**Comment by miyconst** [comment]
Replaced with functions.
