### ISSUE TITLE
When element is removed from partial editor is unable to select anything

### ISSUE THREAD

**Issue by tomalec** [Juicy/juicy-tile-editor#148]
Steps to reproduce:
1. Run Launcher + and app (Products),
2. Open a page with app's partial,
3. Open the editor, reset and save layout,
4. Change the code of an app, and remove one element from HTML partial
5. Refresh the browser,
6. Open the editor.

Nothing is shown in the list view, and I unable to select a thing.

![removed_element](https://cloud.githubusercontent.com/assets/17435/14142086/c80b3860-f683-11e5-98a9-9c25b97ab19f.gif)

**Comment by miyconst** [comment]
Fixed.
