### ISSUE TITLE
Remove old editor

### ISSUE THREAD

**Issue by tomalec** [Juicy/juicy-tile-editor#149]
I think we came so far with new simple editor, that there is no point in keeping old one. 
Especially, that old one does not work http://juicy.github.io/juicy-tile-editor/

It could make the maintenance cheaper, the demo from README could work and present most recent features, etc.

@warpech, @miyconst WDYT?

**Comment by miyconst** [comment]
I agree. Taking this one on me.

**Comment by miyconst** [comment]
Removed, yet to be released.
