### ISSUE TITLE
Sometimes editor shows wrong children in list view

### ISSUE THREAD

**Issue by tomalec** [Juicy/juicy-tile-editor#150]
Steps to reproduce:
1. Run Launcher, Products, Barcodes,
2. Open any product page (http://localhost:8080/products/product/XXXX)
3. Open layout editor
4. Select "Next & prev. buttons"

You will get a list of two "Partial: Full name" which are definitely not there.

![wrong children in the list](https://cloud.githubusercontent.com/assets/17435/15099947/d7af148a-1564-11e6-82e1-3ea496647a75.gif)

@miyconst Could you take a look?

**Comment by miyconst** [comment]
Thank you for reporting the issue. I will take a look tomorrow.

**Comment by tomalec** [comment]
It seems that `refreshSelectedScopeItems` that calls `getNestedLists`
https://github.com/Juicy/juicy-tile-editor/blob/gh-pages/src/juicy-tile-simple-editor.js#L2051
is the problem as selector at  
https://github.com/Juicy/juicy-tile-editor/blob/gh-pages/src/juicy-tile-simple-editor.js#L204
`"[juicytile='Products/2'] juicy-tile-list" is not specific enough, as there are much more`Products/2` around the page.

I believe we could simplify entire flow a lot, and once again use browser instead of re-implementing the wheel. DOM is the API, so lets do some duck-typing-ish work.

I added it to gitbook, at https://starcounter.gitbooks.io/rebelslounge/content/App/Client/Layouts/Layout_editing/layout_editor_navigation_through_elements.html

**Comment by tomalec** [comment]
I have fixed and improved it as described above (almost, as I'm not preparing overall inducted, spanning tree in advance)

@miyconst Please check if you do not have any comments.

**Comment by miyconst** [comment]
@tomalec thank you, I don't have anything to add, the fix seems to be good.
