### ISSUE TITLE
Naming elements

### ISSUE THREAD

**Issue by mattiasmak** [Juicy/juicy-tile-editor#152]
The ability to name the element in code or perhaps in editor should be very helpful. Browsing now is very confusing with many Empty elements... But as with many of my issues. Am I missing something?

**Comment by miyconst** [comment]
@mattiasmak thank you for the question.

This feature was implemented some time ago: https://github.com/Juicy/juicy-tile-editor/issues/126.
Now you can rename elements by double clicking on it.

All you need is the latest `juicy-tile-editor`. I will make sure we have latest in Launcher.

There is also an option to use `juicy-style` attribute. I will come up with an example of how to use it.

**Comment by miyconst** [comment]
Here is an example of how to use `juicy-style` including `itemName` property.
http://juicy.github.io/juicy-tile-editor/examples/juicy-tile-table/juicy-setup.html
