### ISSUE TITLE
Don't try to be smart

### ISSUE THREAD

**Issue by mattiasmak** [Juicy/juicy-tile-editor#153]
Let the developer opt-in or opt-out elements to be affected/edited på editor. 

An attribute like juicyignore could opt-out an element.  These elements should not show up in the list at all.

This is true for us, since we often have web components that do not have a UI at all.

**Comment by miyconst** [comment]
@mattiasmak thank you for the suggestion.
- You can put the elements into a container. All the elements inside will not be visible as a tile.
- `juicy-tile-editor` distributes Light DOM nodes through Shadow/Shady DOM. In shimmed browsers without native Shadow DOM support the non-distributed nodes are physically removed. So, if we ignore such elements inside `juicy-tile-editor` the will not functional. 
- If you want to hide some elements then just specify: `juicy-style="hidden: true"`.

I still think it's possible to implement an `ignore` attribute which would distribute the node at the end of the a partial, but don't show it in the side bar and the editable area.

@tomalec what do you think?

**Comment by tomalec** [comment]
I like the idea of opt-out via attribute.

Currently the `juicy-style="hidden: true"` acts as a "ignore attribute", also all native elements that are non-visual, are not being used by our layouts at all.

The full list of ignored elements:
- has `hidden: true` in `juicy-style` attribute: `<my-element juicy-style="hidden:true;">`
- `instanceof Text`
- `instanceof HTMLLinkElement`
- `instanceof HTMLStyleElement`
- `instanceof HTMLTemplateElement`
- `instanceof HTMLScriptElement`
- `instanceof Comment`

Therefore, for your custom element, that does not extend `link`,`template`, etc. you need to use`juicy-style`.

So the question is whether `juicy-style="hidden: true;"` is enough ar do we really want to have yet another way to set it?

I would like not to introduce too many ways to setup layout properties. (we already have many: `juicy-style`, `defaultTileSetup`, layouts stored in data base, default setup given by `juicy-tile-*`)

**Comment by tomalec** [comment]
I'm closing it as `juicy-tile-*` layouts are not longer supported.

We have moved to vanilla Shadow DOM driven layouts, see https://starcounter.io/layout-compositions-html-partials/

Pleas feel free to re-open or to create a new one, if you want to discuss something related to new layouts and the editor.
