### ISSUE TITLE
Move juicy-color-picker.html to a separate repo

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-tile-editor#17]

**Comment by miyconst** [comment]
@warpech is it still relevant? If so, then `juicy-border-picker` should also be moved. 

We already have lots of repositories, not sure it is good.

**Comment by warpech** [comment]
`juicy-border-picker` should not be moved, because it is of specialised interest. The color picker, on the other hand, is of general interest of choosing color.

It is relevant, because on CustomElements.io there is only one alternative color picker ([color-picker-element](https://github.com/bbrewer97202/color-picker-element)) and it is completely different:

> ![screenshot 2015-05-20 13 12 27](https://cloud.githubusercontent.com/assets/566463/7724455/fdc521f8-fef1-11e4-90b9-014a938b7fe6.png)

Compared to ours:

> ![screenshot 2015-05-20 13 16 17](https://cloud.githubusercontent.com/assets/566463/7724513/6bf0dbd6-fef2-11e4-8a8b-7e5e40d0aad4.png)

**Comment by miyconst** [comment]
Release under version at `1.0.0`

**Comment by miyconst** [comment]
Done.

The repository: https://github.com/Juicy/juicy-color-picker
The demo: http://juicy.github.io/juicy-color-picker

Also added a simple readme.
