### ISSUE TITLE
Add border style picker

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-tile-editor#2]
For the element containers, we should add a border style picker. It should be similar to the background color picker, allowing to choose one of a few predefined border styles (or no border at all - which is default)

**Comment by miyconst** [comment]
Added new `juicy-border-picker` element, it depends on `juicy-color-picker` and looks like on the image:
![juicy-border-picker](https://cloud.githubusercontent.com/assets/6435556/7523061/ccce7cce-f501-11e4-8b10-731738a0653a.png)

**Comment by warpech** [comment]
Serious business, impressive! But the borders render wrong on Chrome/Mac:

![screenshot 2015-05-08 09 47 42](https://cloud.githubusercontent.com/assets/566463/7532453/4f79323a-f567-11e4-9b83-913901f5e516.png)

**Comment by miyconst** [comment]
Could you please check it again? Should be fixed now.

**Comment by warpech** [comment]
Works ok now, thanks
