### ISSUE TITLE
juicy-highlight does not work well with scrolled tiles

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-tile-editor#22]
In `index.html`, `<juicy-highlight>` does not highlight correctly elements of "Nested tiles 2", which is contained in a not visible part of a scrollable div.

It seems that `<juicy-highlight>` puts the border in place that is relative to the container top, left coordinates -  without taking the scrollTop, scrollLeft into account.

**Comment by miyconst** [comment]
It looks like `index.html` of `juicy-highlight` has been changed, there is no more `Nested tiles 2`.
http://localhost:7409/juicy-highlight/index.html

`juicy-highlight` does not work for elements inside scrollable element though. If this is what this issue about, then we should decide how it should work. There may be lots of scrolls of different elements, moreover the element or the page may be scrolled after highlighting.

**Comment by warpech** [comment]
As fair as I remember, the problem is not about about scrolled window, but only about a tile that is inside a scrolled div with `overflow: auto`.

**Comment by miyconst** [comment]
Agreed with @warpech to use `getBoundingClientRect` to comare the previous mask with the new mask.

**Comment by miyconst** [comment]
Done. Released new version.

**Comment by miyconst** [comment]
Also updated demo to show how it works.

**Comment by miyconst** [comment]
Works wrong if the window was scrolled.
