### ISSUE TITLE
Multiselection goes wrong

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-tile-editor#24]
I don't yet have steps to reproduce, but I has this weird effect when clicking on one item in the `juicy-tiles` selected many items in different branches in the `juicy-tiles-tree`.

![multiselection](https://cloud.githubusercontent.com/assets/566463/3064405/62099440-e252-11e3-8a23-073be54293ad.gif)

GIF recorded with [LiceCap](http://www.cockos.com/licecap/)

**Comment by tomalec** [comment]
It is because those tiles shares same setup object.

**Comment by warpech** [comment]
So it is "not a bug"? But bug is that change of width of one element is not reflected in all of its clones

**Comment by tomalec** [comment]
I believe it should be a feature to be able for example to stamp two different `<juicy-tiles>` instances ( from `<template>`) that shares the same setup.

**Comment by warpech** [comment]
Do you think it is possible for two `juicy-tiles` instances in the Launcher to actually come into sharing the same setup object? I can see this useful if use the same template, but we would need to make some magic on setup loading.

**Comment by tomalec** [comment]
I think so, currently we just use exactly same object, so I hope there should be no magic required beside native JS one ;)

**Comment by warpech** [comment]
If we serialize to it JSON and then deserialize, it would not be the same object by default (unless it is stored by the same key)

**Comment by tomalec** [comment]
It will be stored by the same key, as it will be same template URL.
And we plan to fetch it from the server side on per template, so one for every template instances.

**Comment by warpech** [comment]
Closing as Won't fix
