### ISSUE TITLE
Can't set the background color of the root container

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-tile-editor#3]

**Comment by warpech** [comment]
This is dependent on https://github.com/Juicy/juicy-tiles/issues/5

**Comment by tomalec** [comment]
Do we relay want to change background of `<juicy-tiles>` from inside? Shouldn't it be up to owner /host of `<juicy-tiles>` to apply CSS rules to this tag?, and sat it's background color and image?

**Comment by warpech** [comment]
I agree. Closing.
