### ISSUE TITLE
Support for <juicy-tile-grid>

### ISSUE THREAD

**Issue by tomalec** [Juicy/juicy-tile-editor#35]
Currently `JUICY-TILE-LIST` is hardcoded as tagname. Idea is to make it customizable via attribute.

**Comment by tomalec** [comment]
`<juicy-tile-grid>` have specific properties to set, so meybe it should be better to either
1. create `<juicy-tile-grid-editor>` which will extend `<juicy-tile-editor>`, or
2. simply hard-code support for both in `<juicy-tile-grid>`, or
3. make `<juicy-tile-grid>` support grid only, and changing the properties which are not supported by list, will simply make no effect.

**Comment by warpech** [comment]
To finish this task, `<juicy-tile-editor>` needs to hide `<juicy-tile-grid>` editor specific input fields when `<juicy-tile-list>` is in use (as discussed today on a call with Tomek)

**Comment by tomalec** [comment]
Starting from https://github.com/Juicy/juicy-tile-editor/commit/fab83fb56c4f63261f230beebe7ea227cf930ed3 juicy-tile-grid is also attached to editor. The only thing left is to hide `-grid` specific stuff for `-list`, as described above.
