### ISSUE TITLE
Tree menu drop area

### ISSUE THREAD

**Issue by tomalec** [Juicy/juicy-tile-editor#42]
To stick tree menu to the right edge of my browser, I need to drop it few pixels away of the window.

**Comment by miyconst** [comment]
Currently you have to move the top left corner of sidebar closer than 80px to the right edge to stick it to the right side.

You want to calculate position for the right side from the right corner instead of the left, correct?

**Comment by miyconst** [comment]
Distance to the screen edge should be calculated from cursor position, not from the top left corner of sidebar.
