### ISSUE TITLE
Color scheme of the editor

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-tile-editor#44]
Following what @miyconst suggested this morning, I think the current gray color of the editor is a step in a good direction, but can get improved.

Below is comparison with 3 other "gray software": Atom, Visual Studio Code and Brackets:

![screenshot 2015-05-07 17 18 05](https://cloud.githubusercontent.com/assets/566463/7518743/0b9e7adc-f4dd-11e4-8da6-ff2cdb458e3d.png)

I must say that the ">" arrows look the best in our editor! But the color contrast is bad and the text is heavy. Could we apply some fixes to it:

Fonts:
- juicy-tile-editor: 14px, Calibri font (Regular, but looks boldish) - inherited from Launcher, color #FFF
- Atom: 11px, Lucida Grande/Segoe UI (Regular), color #9FA5B3
- Visual Studio Code: 13px, Helvetica Neue (Light), color #FFF
- Brackets: 13px, [Source Sans Pro](https://github.com/adobe-fonts/source-sans-pro) (Regular), color #ADB9BD / #F9F9F9

Line-height:
- juicy-tile-editor: 25px
- Atom: 24px
- Visual Studio Code: 24px
- Brackets: 23px

Backgrounds:
- juicy-tile-editor: #404040
- Atom: #22252B
- Visual Studio Code: #252526
- Brackets: #47484B

What I like the most is colors from Visual Studio Code, font size and font family from Atom and line-height from Brackets.

**Comment by miyconst** [comment]
The result looks like this:

![layout-editor-new-style-0](https://cloud.githubusercontent.com/assets/6435556/7524332/f30d95d4-f509-11e4-8c23-9b56303ac38a.PNG)

The font is ugly as for me.

**Comment by miyconst** [comment]
It looks like those fonts are not supported by chrome, should I include custom fonts?

**Comment by miyconst** [comment]
`Lucida Grande Regular` is available for download here http://www.911fonts.com/font-download/download_LucidaGrandeRegular_6216.htm

**Comment by warpech** [comment]
We should not expect anyone to install a font nor use web fonts (because of privacy and offline availability).

The correct way is to provide CSS font-family fallbacks. Atom does it like this ([source](https://github.com/atom/one-dark-ui/blob/85319143ac6f6f371eba9a05bcc12c14ef44dd97/styles/ui-variables.less#L122)): 

```
font-family: 'Lucida Grande', 'Segoe UI', Ubuntu, Cantarell, sans-serif;
```

The reasoning is that these are the default system UI fonts: Lucida Grande (on OS X, until Mavericks), Seoge UI (on Windows Vista and above), Ubuntu (on Ubuntu, naturally). 

I am not sure why Segoe UI does not render for you. Maybe you forgot to wrap it in quotes?

**Comment by miyconst** [comment]
Probably I just missed something yesterday, `Segoe UI` works fine, `Lucida Grande` does not.

Pushed the changes, the sidebar still looks too small for me.

**Comment by miyconst** [comment]
Closing the issue, because the sidebar was reworked and now looks good.
