### ISSUE TITLE
Move "eye" icon to the side

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-tile-editor#45]
Compare our tree with Sketch and UXPin:

![screenshot 2015-05-07 18 12 19](https://cloud.githubusercontent.com/assets/566463/7520116/af1b36c6-f4e4-11e4-91b7-02338e4d6335.png)

In Sketch, the eye icon is aligned to the **right** border of the panel. In UXPin - to the **left**.

In our case, it is irregular, becuse it is aligned to the label.

What I like the most about Sketch - for the default state (visible), the icon **does not show at all**. The icon only shows in two cases:
- when you put mouse cursor over the tree element
- when the element is in the hidden state

Could we try that?

**Comment by miyconst** [comment]
I like both of the ideas.. but I don't know how to combine them.

Lets say we move the eye icon to the left, so it will be like this:
- [ ] Item 1
- [ ] ---- Item 1.1
- [ ] ---- Item 1.2
- [ ] Item 2
- [ ] ---- Item 2.1
- [ ] ---- Item 2.2

And then hide the icon, there will be a white space gap between the left edge and content. So, the icon should be at the right side or visible all the time.

**Comment by warpech** [comment]
I also think that the left looks better for icons that are always displayed.
The right looks better for icons that are conditionally displayed.

Could you try the right (Sketch) approach first?

**Comment by miyconst** [comment]
Sure.

**Comment by miyconst** [comment]
Okay, a raw version is pushed.

There are a few problems:
1. How to deal with very long names? Should the icon just stick to the right edge and don't scroll? Should it appear at the end of the long name and user have to scroll the sidebar to access the icon?
2. The toggle icon, visible icon, name element, children element are all on the same level and I have to apply `li:hover > .visibility` to show icon on hover, but this also shows icon of the parent group, not sure it is good or bad.

I would like to put toggle icon, visible icon, name element in a container and apply hover style to it, but this would break expand/collapse css `.expand[checked] ~ ul`.

![juicy-tile-tree-0](https://cloud.githubusercontent.com/assets/6435556/7533505/c9f454aa-f57a-11e4-9dec-32206098248d.png)
![juicy-tile-tree-1](https://cloud.githubusercontent.com/assets/6435556/7533506/c9f83c00-f57a-11e4-9104-035636900bcf.png)

**Comment by warpech** [comment]
The above problems are solved after implementing #49, #50.

Closing, thanks!
