### ISSUE TITLE
Demo does not render everything correctly

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-tile-editor#46]
The purpose of the demo available locally after cloning this repo, as well as online at:
- http://juicy.github.io/juicy-tile-editor/
- http://juicy.github.io/juicy-tile-editor/examples/juicy-tiles-grid-editor.html

was to make it easier to develop changes to the editor.

But now it seems to have some issues:
1. it assumes availability of some external resources (like ">" icon in the sidebar)
2. the top toolbar background color is transparent, while the sidebar background color is defined

Could this demo be fixed? Then it will be easier to develop future changes.

**Comment by miyconst** [comment]
Juicy/juicy-tile-editor@b74ae0a9f72d61fcdcb31bcf42febf555a318441

**Comment by miyconst** [comment]
1. Fixed.
2. Also fixed, but we should rework `juicy-tile-editor` to use common styles for top panel and sidebar. Currently sidebar has its own styles.

**Comment by warpech** [comment]
Re: 2. can you start an issue for that?

**Comment by miyconst** [comment]
Done.
