### ISSUE TITLE
Merge styles of juicy-tile-editor-form and juicy-tile-tree

### ISSUE THREAD

**Issue by miyconst** [Juicy/juicy-tile-editor#47]
References to https://github.com/Juicy/juicy-tile-editor/issues/46

Currently styles for `juicy-tile-editor-form` are defined on the containing page like layout or example page, but `juicy-tile-tree` has its own styles.

The styles should be merged and moved to `juicy-tile-editor`.

**Comment by warpech** [comment]
Approved
