### ISSUE TITLE
Cleanup the toolbar buttons

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-tile-editor#48]
We created a lot of buttons and other controls in the layout editor and it starts to get unclear how to use it. 

Some of the buttons work in scope of a single element, other work for all elements in a group or in a juicy-tiles-container.

Steps to continue:
1. Make a list of currently used buttons and controls
2. Group by role
3. Decide how to present them in the UI. Maybe some collapsible menu, conditional hiding or context menu is needed.

**Comment by miyconst** [comment]
- [ ] Should the save button save all changes? Yes, it should. Requires https://github.com/Polyjuice/Launcher/issues/126. Corresponding issue: https://github.com/Polyjuice/Polyjuice/issues/49
- [x]  Remove the "Stack" button.
- [x] Clear button is broken after itemName changes. It looks like the itemName value is not generated after Clear button pressed and new items generated.
- [x] Revert button should revert changes for all juicy-tile-lists, not to selected only.
- [x] Add separator between Save + Revert and other buttons.
- [x] Remove Layout button.
- [x] Replace direction icons with arrows, left -> right, top -> bottom.
- [x] Oversize should work for ~~Groups~~ anything that can have a Background. It is always disabled right now.
- [x] Inner HTML should be enabled for groups only.
- [x] Remove sidebar Reposition icon, place Unhide all button to there.
- [x]  Group to drop down Clear and Reset buttons.
- [x] Group to drop down all "New group" buttons.

**Comment by warpech** [comment]
As an illustration to the above tasks, Image from the meeting between me and @miyconst:

![wp_20150521_12_48_47_pro](https://cloud.githubusercontent.com/assets/566463/7747121/22aee9ba-ffb8-11e4-9355-ae2aabba8f6e.jpg)

**Comment by miyconst** [comment]
@warpech should the Clear button automatically save changes? I don't think so.

**Comment by warpech** [comment]
> @warpech should the Clear button automatically save changes? I don't think so.

I don't think so either.

**Comment by warpech** [comment]
I made some edits to the above checklist

**Comment by warpech** [comment]
Can this be closed? In the above list, not all checkboxes are checked

**Comment by miyconst** [comment]
The only one issue left: `Cannot find function or filter: forceJson` when saving setup for launcher.

**Comment by warpech** [comment]
There is a separate issue for that: https://github.com/Polyjuice/Launcher/issues/126

Closing this one, thanks!
