### ISSUE TITLE
Make the sidebar width resizable

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-tile-editor#49]
To solve problem 1. from https://github.com/Juicy/juicy-tile-editor/issues/45#issuecomment-100168831, please make the sidebar width resizable by dragging the left or right border (so it works when sidebar is attached to left or right edge of the screen).

After this is implemented, remove the horizontal scrolling of the sidebar.

To see the labels of the tree elements that are very deeply nested, the user will need to make the list wider.

**Comment by miyconst** [comment]
Are we going to migrate to Polymer 0.8 https://www.polymer-project.org/0.8/ any time soon?

There is a `core-resizable` https://github.com/Polymer/core-resizable component, which will be deprecated soon. The component is replaced with `iron-resizable-behavior` https://github.com/polymerelements/iron-resizable-behavior which does not support Polymer 0.5.

Should I use any of those components or make my own?

**Comment by warpech** [comment]
Polymer 0.8 and 0.9 don't have all the features in data binding that we use in Polymer 0.5. 

We need to stick with 0.5 at least until 28-29.05.2015, which is the date of Google I/O. Based on previous experience, this event coincidents with Polymer update announcements.

> Btw. Google I/O 2015 website is developed with Polymer 0.5.5 ;)

Maybe create our own resizable element, based on https://github.com/Polymer/core-resizable, https://github.com/polymerelements/iron-resizable-behavior and/or https://github.com/manekinekko/drag-resize?

**Comment by miyconst** [comment]
The `drag-resize` component seems to be very cool, but it has a lot of dependencies, and we already have dragging. That is why I decided to create own simple component.

The new components `juicy-resizable` is very simple, but does what we need in layout editor. Resize works in horizontal direction only, the vertical direction could be easily added, if needed.

The sidebar remembers it's width, not only position. So, each user may choose left/right position and width, the values are stored in `window.localStorage`.

**Comment by miyconst** [comment]
The working demo is available http://juicy.github.io/juicy-tile-editor/.
