### ISSUE TITLE
Make juicy-toggle-icon-button data bindable

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-tile-editor#50]
Currently, there are problems with the sidebar coming from the fact that `<juicy-toggle-icon-button>` attribute "checked" only allows to work with sibling CSS selector:

> 1. The toggle icon, visible icon, name element, children element are all on the same level and I have to apply li:hover > .visibility to show icon on hover, but this also shows icon of the parent group, not sure it is good or bad.
> 
> I would like to put toggle icon, visible icon, name element in a container and apply hover style to it, but this would break expand/collapse css .expand[checked] ~ ul.

Make `<juicy-toggle-icon-button>` data bindable (without breaking the current functionality) so it can be bound to boolean properties like "highlighted" or "expanded".

**Comment by miyconst** [comment]
Done, but a question appears. Should the collapse/expand state will be saved with tile setup?

If yes, then the button should toggle dirty state of _Save_ button.
If no, then it should be removed from `item` and stored in `juicy-tile-tree` only.

**Comment by miyconst** [comment]
This allowed me to finally format ugly html: 

Before:

``` html
<juicy-toggle-icon-button ...></juicy-toggle-icon-button
><juicy-toggle-icon-button ...></juicy-toggle-icon-button
><div></div>
```

Now:

``` html
<juicy-toggle-icon-button ...></juicy-toggle-icon-button>
<juicy-toggle-icon-button ...></juicy-toggle-icon-button>
<div></div>
```

**Comment by warpech** [comment]
The collapse/expand state should not be saved with the setup. Do you have an idea how to remove the state from `item` then?

**Comment by miyconst** [comment]
All of our items have unique id, so it should be something like `juicy-tile-tree.collapsed[item.id]`.

**Comment by miyconst** [comment]
This rework broke _Scroll to selected element_, should be fixed. Just note here to don't forget.
