### ISSUE TITLE
Need a way to create empty groups

### ISSUE THREAD

**Issue by miyconst** [Juicy/juicy-tile-editor#52]
I found that empty groups could be used as white space gap, it is some king of hacking, but still useful.

For example, I need to add border for an input. Our default bootstrap theme adds bottom border for all inputs. So, after applying outline it looks ugly.

I did like this:
1. Select input.
2. Create a new group.
3. Drag input to the parent's group.
4. Add some height to the empty group.
5. Select input and the empty group.
6. Put them into a new group.
7. Apply outline to the new group.

We should either let user create a new empty group, or does not let user create empty groups at all.

**Comment by warpech** [comment]
@tomalec says he's ok with it for multiple reasons, so let's go with it. It can also be used to create a group to which some elements are moved.

I'm ok as well!

**Comment by miyconst** [comment]
Done.

Also moved _Ungroup_ button to the _Goup actions_ buttons set.
Fixed _Ungroup_ button availability for root container.
