### ISSUE TITLE
Replace icons with an icon font

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-tile-editor#53]
We decided to use following icons from Font Awesome:
- Save - save
- Revert - undo
- Clear - eraser
- Source - wrench (maybe there's a better idea?)
- Direction - hand-o-down / hand-o-right (becomes a toggle icon)
- Gutter - `<input>`
- Oversize - `<input>`
- New Group - plus-square-o
- Move to group - sign-in
- Unroup - minus-square-o
- Inner HTML - code
- Fill - tint
- Outline - pencil-square-o
- Width - `<input>`
- Height - `<input>`
- Priority - `<input>`

Sidebar:
- "Elements" - reduce font size, add padding, change background color or add bottom border
- Expand - angle-right
- Collapse - angle-down
- Juicy Tile List - th-large
- Group - _no icon_
- Element - _no icon_
- Show - eye
- Hide - eye-slash
- Hide - eye-slash

The icon font (custom name "Juicy Tile Editor Icons", CSS prefix "jte-icon") should be generated using fontello.com. 

Select only the icons that are listed above (the font can be later re-generated using fontello's config.json). 

Check the whole package generated by fontello to `juicy-tile-editor`.

**Comment by miyconst** [comment]
`Outline` also does not require icon. Other done.

**Comment by warpech** [comment]
For future consideration - there is now a rich and size-optimized icon font from Google: http://google.github.io/material-design-icons/ (list of icons: https://www.google.com/design/icons/)

I'm not particularly loving it, but good to know!

**Comment by miyconst** [comment]
Very solid icon collection, the names are a bit strange though, the `car` icon is named as `time to leave` :laughing:
