### ISSUE TITLE
Static width of root containers causes dirty state of each juicy-tile-list

### ISSUE THREAD

**Issue by miyconst** [Juicy/juicy-tile-editor#58]
Currently I cannot apply `100%` width to parent container of `juicy-tile-list`, the value is automatically being changed to actual width of the container.

To avoid scrolls on small monitors I manually replace values with `100%`, the styles works fine, but layout editor reverts value on open and all of the `juicy-tile-lists` became dirty. 

If a page has a set of the same `juicy-tile-list`, for example a person has some addresses, then we have to apply styles to the last `juicy-tile-list`, otherwise the changes will not be saved. Here is an example:
1. Person page.
2. Three addresses and `juicy-tile-list` for each of them.
3. The first `juicy-tile-list` has got a new style.
4. User presses `Save` button.
5. `juicy-tile-editor` iterates throught each dirty `juicy-tile-list` and saves it's setup.

The list which has actual changes is the first one, so it will be saved first, but the second one also has changes, it's width was changed from `100%` to some static value. And now it's setup also saved, which overwrites setup from the first `juicy-tile-list`.

**Comment by warpech** [comment]
@tomalec: should @miyconst find a fix for this or will it be automatically fixed in juicy-tiles-list `repackSeparation` branch?

**Comment by tomalec** [comment]
Even if it would not be fixed, it should be definitely fixed after separation is done.

**Comment by miyconst** [comment]
@tomalec, I think this is already fixed, correct?

**Comment by tomalec** [comment]
I would say so, as now width of juicy-tile-list means something else ;)
