### ISSUE TITLE
Impossible to drag a tree element to the root

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-tile-editor#62]
In sidebar tree it is possible to drag tree elements from the `juicy-tile-list` root level to a group and between groups, but it is not possible to drag from a group to the root level.

Using "To group" button allows to move elements from a group to the root level as expected.

![screenshot 2015-06-03 10 27 50](https://cloud.githubusercontent.com/assets/566463/7955799/55c09736-09db-11e5-8cd6-71e002fa53ab.png)

**Comment by miyconst** [comment]
Taking this one.
