### ISSUE TITLE
Implement UI for the "first break point"

### ISSUE THREAD

**Issue by tomalec** [Juicy/juicy-tile-editor#65]
Once https://github.com/Juicy/juicy-tile-grid/issues/9 is ready, we need to make sure that it works well with editor, plus we could provide debugging hint with current element size, to make determining context value easier for the designer.

**Comment by tomalec** [comment]
I've implemented it so it uses good, old width/height input. @miyconst Please check, how usable it is, as I'm not sure that "current element size" is what we need, and how confusing will it be ;)

**Comment by miyconst** [comment]
I am a bit confusing, how should I test it?

**Comment by tomalec** [comment]
Set the width for `<juicy-tile-grid>` element using editor, It should set the packing/CSS generating context, which then will be used after page-reload/ at other machine etc.

So this should solve a problem with:
1. Setup layout
2. Resize the window
3. Reload the page/load it from the browser in different window size.

**Comment by miyconst** [comment]
With those new changes I can't setup layout I want. Some guides from @tomalec would be needed.

**Comment by miyconst** [comment]
After short (maybe not that short) explanation from @tomalec of how to use it, I see it very reasonable and straight forward.

Current state is not ready to merge to `gh-pages` branch though, tight groups are required.

**Comment by miyconst** [comment]
Closing the issue as it is implemented and merged to master branch.
