### ISSUE TITLE
Improve width/height popup

### ISSUE THREAD

**Issue by miyconst** [Juicy/juicy-tile-editor#67]
The width/height popup dialogs was made before fractions, they need some adjustments now.

I think, this one looks good:

![new-width-popup](https://cloud.githubusercontent.com/assets/6435556/8528881/e5ce0590-241e-11e5-8299-36fde94e051c.png)

@tomalec  what do you think?

**Comment by tomalec** [comment]
Looks cool :) especially with "Actual width".

Maybe it's also a time to rename `auto` to `pre-calculate` alt least for UI?
https://github.com/Juicy/juicy-tile-list/issues/30

**Comment by miyconst** [comment]
I have improved width/height popups, but I don't like the way it works.

To access the real tile I shared `juicy-tile-editor` with `juicy-tile-editor-form` via parameter and get dimension like `this.editor.selectedElements[0].getBoundingClientRect()`.

I would like to keep `juicy-tile-editor-form` not aware from `juicy-tile-editor`.

**Comment by miyconst** [comment]
Let's keep the discussion about `auto` in it's issue.

**Comment by tomalec** [comment]
Why can't you use just `this.selectedItems` as in other methods?

**Comment by miyconst** [comment]
`this.selectedItems` is an array of tile setup objects, not of actual tiles, am I missing something?

**Comment by tomalec** [comment]
you can iterate over them, and fetch tile by id.  However keeping a reference to editor should be easier and faster.

`-tree` is also aware of editor, isn't it? So maybe we should just live with the fact that they are not so independent components.

**Comment by miyconst** [comment]
> you can iterate over them, and fetch tile by id

Actually, I cannot. The tiles have ids of number, like `0`, `1` and this makes it impossible.
- `document.getElementById("0")` returns nothing, because the tiles are inside shadow dom.
-  `document.querySelector("#0")` throws an exception `Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#0' is not a valid selector.`.

**Comment by tomalec** [comment]
But you can use `.tiles` map
9 lip 2015 10:08 "Konstantin" notifications@github.com napisał(a):

**Comment by miyconst** [comment]
Yes, this one looks much better, don't know how I missed it out.

I removed reference to `juicy-tile-editor` from `juicy-tile-editor-form` and used the collection you specified.

Closing the issue.
