### ISSUE TITLE
Add tile dimensions to highlight element

### ISSUE THREAD

**Issue by miyconst** [Juicy/juicy-tile-editor#68]
Me and @tomalec think, that it would be nice to add width/height values and actual tile dimensions to highlight element of a tile.

It should be a small rectangle in the top left corner with some text like:

```
100% x 10
1000px x 10px
```

**Comment by miyconst** [comment]
There are some ways to achieve this feature:
1. Teach `juicy-highlight` to display it's content with the highlight svg.
2. Add a new `juicy-highlight-with-content` element, which would use `juicy-highlight`, but also add the content.
3. Teach `juicy-tile-list` to not only highlight tile, but also display some content for it.

I vote for solution 1.

**Comment by tomalec** [comment]
I vote for 1 as well.

**Comment by miyconst** [comment]
I improved `juicy-highlight.show` function, now it is:

``` js
JuicyHighlightPrototype.show = function (elements, getContent) {
...
}
```

`getContent` - function which is being called per each focused element. The return value of the function is shown in the top left corner of the element.

**Comment by miyconst** [comment]
Done. Now actual tile size is shown inside hover `juicy-highlight`.

There is an issue though, moving mouse to the content acts like `blur` of tile, which hides the `juicy-highlight`.

**Comment by miyconst** [comment]
After playing some more time I changed behaviour, now display actual tile size of selected tiles, not of hovered tiles.

This does not hides size on `tile.blur` and lets see size of multiply tiles simultaneously. 

Looks like this:

![actual-tile-size](https://cloud.githubusercontent.com/assets/6435556/8579157/a0b58872-25bb-11e5-8b4f-0d13fae43468.png)

**Comment by tomalec** [comment]
Great,
It is an actual size, not the setup one?

**Comment by miyconst** [comment]
Yes, it is actual tile size in `px`. Do you also want to see the _setup size_?

**Comment by tomalec** [comment]
Yes

**Comment by miyconst** [comment]
Okay, next screenshot: 

![image](https://cloud.githubusercontent.com/assets/6435556/8591862/c9c22ba8-2633-11e5-9aa0-b3d6f307d8a6.png)

**Comment by miyconst** [comment]
Please, close the issue if you think it is good.

**Comment by miyconst** [comment]
@tomalec can this one be closed?

**Comment by tomalec** [comment]
Yes, thanks
