### ISSUE TITLE
Remove console errors from demos

### ISSUE THREAD

**Issue by miyconst** [Juicy/juicy-tile-editor#69]
Currently both of the demos throws some exceptions on save button click:

![console](https://cloud.githubusercontent.com/assets/6435556/8529086/6fd1323e-2420-11e5-8708-297d4f103c64.png)

Those errors should be fixed.

**Comment by miyconst** [comment]
Error 1 fixed, others require mock server, not sure it worth the effort.

**Comment by warpech** [comment]
Definitely not. Thanks!

**Comment by miyconst** [comment]
This errors will be gone once we move to Polymer 1.1, as I reworked `juicy-tiles-setup-sync` to have an option to save to local storage, and not try to push changes to server no matter what.
