### ISSUE TITLE
Invalid height: auto calculations

### ISSUE THREAD

**Issue by miyconst** [Juicy/juicy-tile-editor#70]
In the `juicy-tiles-grid-editor.html` demo height for highlight element being calculated incorrectly if tile's height is auto.

![invalid-height-auto](https://cloud.githubusercontent.com/assets/6435556/8529557/e0759d42-2423-11e5-8dcc-d6dd036893f2.png)

Here is the setup I use:

```
{"id":"root","direction":"rightDown","gutter":25,"items":[{"width":"25%","height":50,"priority":0.5,"id":"0","itemName":"0 widthFlexible: fal …","hidden":false,"widthFlexible":true,"heightAuto":true},{"width":"25%","height":50,"priority":0.4375,"id":"1","itemName":"1 widthFlexible: tru …","hidden":false,"widthFlexible":true,"heightAuto":true},{"width":"25%","height":55,"priority":0.3828125,"id":"2","itemName":"2","hidden":false,"widthFlexible":true,"heightAuto":true},{"width":"25%","height":55,"priority":0.3349609375,"id":"3","itemName":"3: widthFlexible: true","hidden":false,"widthFlexible":true,"heightAuto":true},{"width":256,"height":128,"priority":0.2930908203125,"id":"4","itemName":"4","hidden":false},{"width":256,"height":128,"priority":0.2564544677734375,"id":"5","itemName":"5","hidden":false},{"width":256,"height":128,"priority":0.2243976593017578,"id":"6","itemName":"6","hidden":false},{"width":256,"height":128,"priority":0.19634795188903809,"id":"7","itemName":"Subitem 0 Subitem 1  …","hidden":false}],"width":1650,"heightAuto":true,"itemName":"st1"}
```

@tomalec should I investigate this?

**Comment by tomalec** [comment]
If you can, I bet it's because of margins in elements inside the tile.

**Comment by miyconst** [comment]
During investigation I found another very strange behaviour:
![juicy-tile-wrong-height](https://cloud.githubusercontent.com/assets/6435556/8570300/1c769796-2588-11e5-90e1-880d5f64c2bf.png)

The tile height is calculated and set correctly to `128px`, but chrome displays it as `50px`. I disabled all animation styles for tiles, but the bug is still here.

`min-height` does not solve the problem, `height: 128px!important` solves the problem, but it is an ugly hack.

**Comment by miyconst** [comment]
Similar situation with the first issue.

The tile height is being calculated by: `tile.scrollHeight`, even thought the height style was removed `tile.style.height = "";` Chrome still does not return correct value.

In Chrome debugger I see wrong value for `tile.scrollHeight`, but as soon as I navigate to actual `div` inside the tile and check it dimensions the `tile.scrollHeight` value changes to the right one.

**Comment by tomalec** [comment]
Regarding the second issue you described, I've seen it before, and thought it's only bug in Chrome debugger, as tile is displayed correctly, and I thought Chrome fails to show dimensions of (experimental/available under the flag) CSS Grid within shadow DOM (still fresh feature) .

But now, you pointed out, that it affects our highlighter, so we need to address that.

**Comment by miyconst** [comment]
Our highlighter paints on top of `juicy-tile`, and the `juicy-tile` has wrong dimensions. 

We could paint the highlight over real html element instead of `juicy-tile`, but it won't work with groups.

**Comment by tomalec** [comment]
I think we should highlight `juicy-tile`, and fix it's dimensions somehow.

**Comment by miyconst** [comment]
Looks like `!important` does not solve the issue if it is set with `height` value.

Setting height style in timeout solves:

`juicy-tile-grid.js line: 199`

``` js
setTimeout(function () {
    elementStyle.height = packedItem.heightFlexible ? "100%" : packedItem.height + "px";
});
```

Not sure whether it is a good idea, but it works. Any thoughts?

**Comment by miyconst** [comment]
Closing this issue as outdated.
