### ISSUE TITLE
Height in %, how to use it?

### ISSUE THREAD

**Issue by miyconst** [Juicy/juicy-tile-editor#71]
When I apply height in % to a tile it jumps to the top position of all other tiles.

![tile-static-height](https://cloud.githubusercontent.com/assets/6435556/8529927/9ef187b6-2426-11e5-8077-fbdbb27a3525.png)

![tile-precent-height](https://cloud.githubusercontent.com/assets/6435556/8529930/a32f32d8-2426-11e5-975e-beefb3dbb1df.png)

The questions: 
1. What is the 100% of height?
2. Why the tile with height in % jumps to the top?

The layout setup:

```
{"id":"root","direction":"rightDown","gutter":25,"items":[{"width":"25%","height":80,"priority":0.5,"id":"0","itemName":"0 widthFlexible: fal …","hidden":false,"widthFlexible":true,"heightAuto":false},{"width":"25%","height":80,"priority":0.4375,"id":"1","itemName":"1 widthFlexible: tru …","hidden":false,"widthFlexible":true,"heightAuto":false},{"width":"25%","height":80,"priority":0.3828125,"id":"2","itemName":"2","hidden":false,"widthFlexible":true,"heightAuto":false},{"width":"25%","height":80,"priority":0.3349609375,"id":"3","itemName":"3: widthFlexible: true","hidden":false,"widthFlexible":true,"heightAuto":false},{"width":256,"height":128,"priority":0.2930908203125,"id":"4","itemName":"4","hidden":false},{"width":256,"height":128,"priority":0.2564544677734375,"id":"5","itemName":"5","hidden":false},{"width":256,"height":"50%","priority":0.2243976593017578,"id":"6","itemName":"6","hidden":false},{"width":256,"height":300,"priority":0.19634795188903809,"id":"7","itemName":"Subitem 0 Subitem 1  …","hidden":false}],"width":1650,"heightAuto":true,"itemName":"st1"}
```

cc @tomalec

**Comment by tomalec** [comment]
as the `"%"` dimensions are related to the size of the parent container, probably we should block setting it when related size is unlimited/`Infinity`. 

> What is the 100% of height?

It's 100% of containers height, so it makes sense, if your container have delimited height. The root container have packing dimensions set to infinity (for `"rightDown" it's height). So the straightforward solution is either to change the direction, or pack tile into a group with finite size.

> Why the tile with height in % jumps to the top?

It's not "the tile with height in %" that jumps to the top, it's "the tile that does not fit into its container".
If you try to pack a tile `1000x1000` to a `100x100` container it will be placed at `0,0` as there is no better place for it. 

I can investigate the 0,0 effect, as `256x50%*Infinity` should fit into `1650xInfinity`.
But the general issue with % of unlimited size is still there (It also affect width for opposite direction)

**Comment by miyconst** [comment]
Thank you for the explanation.
