### ISSUE TITLE
Changes inside a nested juicy-tile-grid does not trigger dirty state of save button

### ISSUE THREAD

**Issue by miyconst** [Juicy/juicy-tile-editor#72]
Steps to reproduce:
1. Open the `juicy-tiles-grid-editor.html` demo page.
2. Clear setup.
3. Reload page.
4. Save setup.
5. Reload page.
6. Change width/height of any tile inside nested `juicy-tile-grid`.
7. The save button will stay disabled, but should be enabled.

![nested-juicy-tile-grid-bug](https://cloud.githubusercontent.com/assets/6435556/8530314/f7ccabd4-2428-11e5-86b9-a3073a60f98f.png)

Those values also not being saved when dirty state is triggered by some other change.

cc @tomalec

**Comment by miyconst** [comment]
This happens because nested `juicy-tile-grid` does not have `juicy-tiles-setup-sync`.

The `juicy-tiles-setup-sync` assigns itself to `juicy-tile-grid`:

``` js
attached: function() {
    // wait for bindings are all setup
    globme = this;
    this.tileList = this.nextElementSibling;
    // this.currentValue = this.tileList.setup;
    this.tileList.sync = this;
}
```

I think this should be reworked and `juicy-tiles-setup-sync` should be set to `juicy-tile-list` by parameter.

**Comment by miyconst** [comment]
@tomalec what do you think?

**Comment by tomalec** [comment]
I think it shouldn't as we plan not to attach editor and all json related
stuff to DOM if not needed/requested.
9 lip 2015 12:43 "Konstantin" notifications@github.com napisał(a):

**Comment by miyconst** [comment]
Okay, then I close this issue as non relevant.
