### ISSUE TITLE
Add UI to align the grid cell content

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-tile-editor#78]
In layout editor, we need a way to align the content of the cell.

Here is how it looks in other software. From the examples that I found, I like Word 2010 and Word for Mac 2011 the most.

PowerPoint 2007:
<img width="338" alt="screenshot 2015-08-04 16 26 50" src="https://cloud.githubusercontent.com/assets/566463/9063012/f1a895ca-3ac5-11e5-8688-c62822f50370.png">

Word 2010:
<img width="303" alt="screenshot 2015-08-04 16 27 02" src="https://cloud.githubusercontent.com/assets/566463/9063016/f617268a-3ac5-11e5-8f0a-3ecbb70db0f2.png">

Word for Mac 2011:
<img width="172" alt="screenshot 2015-08-04 16 25 55" src="https://cloud.githubusercontent.com/assets/566463/9063010/ed3613b4-3ac5-11e5-8ba6-376d8e30ddbd.png">

Keynote:
<img width="125" alt="screenshot 2015-08-04 16 33 44" src="https://cloud.githubusercontent.com/assets/566463/9063204/a614170a-3ac6-11e5-8b26-a09aea844931.png">

Create an issue in juicy-tile-grid if needed.

**Comment by tomalec** [comment]
I would pick an icon, similar to ones above, but with single rectangle inside, instead of lines. We are aligning single content box inside, and those icons suggest lines/tiles alignment as with `direction`, `rightToLeft`, etc.

**Comment by miyconst** [comment]
Something like this: ![image](https://cloud.githubusercontent.com/assets/6435556/9163329/3eb80c34-3f52-11e5-8bdd-b579eb9b40e0.png) ![image](https://cloud.githubusercontent.com/assets/6435556/9163337/4255fc70-3f52-11e5-8154-ff3c588990d7.png) ![image](https://cloud.githubusercontent.com/assets/6435556/9163350/493309a2-3f52-11e5-974f-f4c13333d93d.png)?

There is no such icons in font-awesome, but it can be simulated with `th-large` or `stop` icons: http://fortawesome.github.io/Font-Awesome/icons/.

**Comment by warpech** [comment]
I guess @tomalec means a small rectangle inside a bigger rectangle, right? This can actually be simulated with an `<span style="display: inline-block">`

**Comment by miyconst** [comment]
Yeah, I just meant that.

**Comment by tomalec** [comment]
I think, div/stop icon inside a div with border should be enough.

**Comment by miyconst** [comment]
On one of the meeting with @warpech, @tomalec, @Starcounter-Jack, and me, we discovered such control:

![image](https://cloud.githubusercontent.com/assets/6435556/12750435/9abe9d50-c9b7-11e5-859a-addec9e0c1a5.png)

It is already implemented and waiting for support from `juicy-tile-list/grid/table`.
