### ISSUE TITLE
Rename width/height property labels

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-tile-editor#79]
Currently we have the following property labels in width and height:
- precalculate
- flexible
- dynamic

<img width="216" alt="screenshot 2015-08-04 17 53 45" src="https://cloud.githubusercontent.com/assets/566463/9065450/dc396de8-3ad1-11e5-92a3-c79fdc075591.png">

Let's think of better names that reflect the **effect** of the property.

As discussed on today's meeting, "dynamic" should be renamed to "resize with content". What about "precalculate"? "Flexible" seems ok.

/cc @tomalec, @miyconst, @Starcounter-Jack

**Comment by miyconst** [comment]
We also agreed to replace `precalculate` checkbox with a button `calculate`, the button would calculate value and set it to the input.

**Comment by tomalec** [comment]
Replace, or add side by side?

Replacing would simplify flow definitely.

But, I would leave precalculate feature in juicy-tile-list code, just in case:
1. We will change our mind,
2. We would need it for some fallback/shims

**Comment by warpech** [comment]
I think _replace_. The purpose is to remove the need to prerender the elements before applying the layout (this is important for https://github.com/Polyjuice/Polyjuice/issues/58).

Of course we can leave the feature somehow in code, but we should never use it ourselves, because it drastically affects performance.

**Comment by miyconst** [comment]
I agree with @warpech, the feature could stay in `juicy-tile-list` and `juicy-tile-grid`, but don't use it in `juicy-tile-editor`.

**Comment by tomalec** [comment]
Agree.

> the feature could stay in juicy-tile-list and juicy-tile-grid, but don't use it in juicy-tile-editor

That's exactly what I thought about :)

**Comment by miyconst** [comment]
Done.

I use the `precalculate: true` to get the calculated dimensions.

**Comment by miyconst** [comment]
This is how it looks like.

![image](https://cloud.githubusercontent.com/assets/6435556/9105375/ba24e152-3c1f-11e5-86ee-942cb8f97fce.png)

**Comment by miyconst** [comment]
@warpech, @tomalec, should I release new version of `juicy-tile-editor` and propagate this to Launcher?

**Comment by miyconst** [comment]
Released with @12a951ec447a8929d8baad4b209addeb138cf73c
