### ISSUE TITLE
Add possibility to drag elements in the side panel to change priority

### ISSUE THREAD

**Issue by miyconst** [Juicy/juicy-tile-editor#80]
It should be possible to drag elements in the side panel to change their priority. Right now we can resort elements (change priority) by clicking `+`/`-` buttons only.

cc @warpech, @tomalec

**Comment by warpech** [comment]
Agreed that this is a nice addition, but low priority

**Comment by miyconst** [comment]
Was decided to remove this feature in `juicy-tile-simple-editor`.
