### ISSUE TITLE
Show the elements tree on the right side of the window by default

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-tile-editor#81]
Like this:
<img width="1313" alt="screenshot 2015-08-10 12 46 04" src="https://cloud.githubusercontent.com/assets/566463/9169776/cbe3ad74-3f5d-11e5-8724-40836af19e22.png">

**Comment by miyconst** [comment]
Released with @12a951ec447a8929d8baad4b209addeb138cf73c
