### ISSUE TITLE
Width/height inputs are disabled with precalculate: true

### ISSUE THREAD

**Issue by miyconst** [Juicy/juicy-tile-editor#82]
The precalculate checkbox is removed (https://github.com/Juicy/juicy-tile-editor/issues/79), but the default tile style is `precalculateHeight: true`. This leads to disabled height input by default, and requires user to press _Calculate_ button to enable it.

Possible solutions: 
1. Change default style, this leads to very ugly and overlapping layout on first page load.
2. Do not disable width/height inputs even if `precalculate: true`. Set `precaclulate: false` if user tries to edit the value by inputting text or by pressing the `+`/`-` buttons.

This example should also be reworked or removed: https://github.com/Juicy/juicy-tile-editor/blob/gh-pages/examples/juicy-tile-grid/demo.html#L163

cc @tomalec

**Comment by tomalec** [comment]
+1 for 2.

**Comment by warpech** [comment]
I vote for 2 as well. @miyconst can you do it?
