### ISSUE TITLE
Fix or remove highlight tooltip

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-tile-editor#83]
There are few problems with the highlighted element tooltip:
1. The values written on red semitransparent background are sometimes ureadable
2. The values are not updated when the element or the window is resized

Because of that, I think that the tooltip needs general improvements or it should be removed. I think it is not very useful, since the same information is repeated in "width" and "height" field dropdown.

@miyconst WDYT?

<img width="1149" alt="screen shot 2015-08-14 at 12 27 49" src="https://cloud.githubusercontent.com/assets/566463/9272165/0052af7c-4280-11e5-85d8-375b71834c1e.png">

**Comment by miyconst** [comment]
I almost agree with you. @tomalec asked for this tooltip.

I don't see how it could be effectively improved since it is too big to make it non-transparent, and there is no way to reduce it in size and keep the content.

The tooltip is actually very handy from time to time.

My suggestion is to remove second line from the tool tip, and shorten the first one to contain only size, without the word `Size`. Then it would look nice without transparency.

**Comment by warpech** [comment]
> My suggestion is to remove second line from the tool tip, and shorten the first one to contain only size, without the word Size. Then it would look nice without transparency.

Sounds fine! Please round the size with 2-digit precision, if possible. Is it possible to refresh the size when the element of window is resized?

**Comment by miyconst** [comment]
Done. New look:

![image](https://cloud.githubusercontent.com/assets/6435556/9273956/eafd5a5e-4299-11e5-8ff1-48eb58be3cd3.png)

**Comment by warpech** [comment]
Can you show the decimal value only if it's different than ".00"?

**Comment by miyconst** [comment]
![image](https://cloud.githubusercontent.com/assets/6435556/9276049/49fe7672-42aa-11e5-8f38-04ae65d891f5.png)

Like this? Why do we even need those decimals of a pixel? Maybe cut them all off?

**Comment by warpech** [comment]
Maybe cut them off totally, sure!

**Comment by miyconst** [comment]
Done.

New look:

![image](https://cloud.githubusercontent.com/assets/6435556/9300222/59932618-44cc-11e5-821f-b9496b3e676e.png)
