### ISSUE TITLE
Add possibility to set height of element to 100% of screen

### ISSUE THREAD

**Issue by miyconst** [Juicy/juicy-tile-editor#89]
This feature was requested by @mattiasmak just now.

**Comment by miyconst** [comment]
@tomalec this is already implemented, right?

**Comment by tomalec** [comment]
Right. 
https://github.com/Juicy/juicy-tile-grid/issues/27
All you need it to specify `height: "100%"` for a tile, and container needs any non-zero height (first break-point). Naturally, you need to set some height using CSS to `<juicy-tile-list>`/`-grid>`
