### ISSUE TITLE
UI and Usability suggestions

### ISSUE THREAD

**Issue by miyconst** [Juicy/juicy-tile-editor#93]
I was thinking of how to improve the UI and Usability of the layout-editor over night and come up with the next ideas:
- 1. Disable Height when a `juicy-tile-grid` selected.
- 2. Rename Width to Dots and add a title "Number of horizontal dots per row".
- 3. A dot should equal to a px when editing, even if there are some more space left on the screen.
- 4. Rid off "flexible" checkbox by providing expressions and "dt" measure unit, which are much more simple to explain.
- 4.1. `width: 100px` - 100 pixels in width, not flexible, (one hundred pixels).
- 4.2. `width: 100dt` - 100 pixels in width, flexible, (one hundred dots).
- 4.3. `width: 100% - 100px` - flexible tile which occupies entire width minus 100 pixels.
- 4.4. `width: 100% - 100dt` - flexible tile which occupies entire width minus 100 dots.
- 5. % value means that the tiles is flexible.
- 5.1. As for now we support % values for non-flexible tiles. For the convenience a % <-> px <-> dt converter should be made. Something like: user enters value in %, then wants to make the tile be same width, but not flexible, converts it to px by a simple button press.
- 6. When the "resize with content" option presses the titles should change to "min-width" and "min-height".
- 7. Automatically skip hidden tiles when moving a tile with priority "+" and "-" buttons.

cc @tomalec, @warpech, @Starcounter-Jack

**Comment by tomalec** [comment]
I do not like introducing `dots` as it would be another magical juicy specific thing to explain, maybe we should call it `fractions` - as that is what flexible size really is, so at least the devs familiar with latest CSS spec, would get it faster.

ad 2. I'm not sure if it would be clear what does it mean, as it is not the width of your conatainer all the time.

ad. 5. I think quite often you would like to make a tile 25% and see this value there, as 367px out of 1468dt/fr written somewhere else is hard to get for me.

**Comment by miyconst** [comment]
Closing this issue as we came up with better solution: simple/advanced mode.
