### ISSUE TITLE
The width/height inbox should reflect the input value (preparsed string) rather than the pixel value 

### ISSUE THREAD

**Issue by Starcounter-Jack** [Juicy/juicy-tile-editor#94]
<img width="347" alt="screenshot of google chrome 13-01-16 12-33-28" src="https://cloud.githubusercontent.com/assets/1219049/12293159/dd2f07a4-b9f1-11e5-8cf1-fc92832895fe.png">

The width is 100% rather than 956 pixels.

**Comment by miyconst** [comment]
This label was intended to show actual tile dimension, but not the tile's setup.

Anyway, it was completely removed in the new version of the editor.
